### PR TITLE
feat: Support format document in vscode

### PR DESCRIPTION
**Pull request by weirongxu**

### CODE REVIEW

**Comment by weirongxu** [comment]
Could you review this? @bd82

**Comment by bd82** [comment]
Hi @weirongxu 

What does `vscodeLanguageIds: ["toml"]` do?
does it cause VSCode Prettier extension load this plugin? or something else?

**Comment by weirongxu** [comment]
> does it cause VSCode Prettier extension load this plugin?
Yes, Prettier extension will load this plugin, and support format the toml document.

Examples of other plugins:
https://github.com/prettier/plugin-php/blob/9917045bab9723056a813879eb75dc092bb6f33b/src/index.js#L37
https://github.com/jhipster/prettier-java/blob/7714aeb2654b3fbae05059ba2c87d94fd8397001/packages/prettier-plugin-java/src/index.js#L17

**Comment by bd82** [comment]
o.k. @weirongxu thanks for the references. 👍

**Comment by bd82** [comment]
I am trying to release but the travis build seems to have failed due to some apt-get error.
- https://travis-ci.org/github/bd82/toml-tools/jobs/681135670

I will try again tomorrow.
@weirongxu do you have any in depth interest in Toml / Toml-Tools?
I am asking because this repo could use another maintainer 😄

**Comment by weirongxu** [comment]
> I am asking because this repo could use another maintainer

But I'm worried that I don't have much time to maintain it recently.

**Comment by kinosang** [comment]
It seems the failed is not caused by apt nor ppa, it's because your npm token is invalid.

https://travis-ci.org/github/bd82/toml-tools/jobs/681136994#L437-L439

**Pull request merged**
